### ISSUE TITLE
Miglioramenti

### ISSUE THREAD

**Issue by fctaddia** [AleP04/LineCalc#1]
Ciao ho trovato il tuo progetto molto interessante. Ho deciso di scaricarlo e di metterci un po' le mani. Ho sistemato grossi problemi grafici e snellito l'xml così da rendere l'app più reattiva e alla portata di tutti gli schermi.
Fammi sapere se ti interessa il mio aiuto.

**Comment by AleP04** [comment]
Buon pomeriggio, comincio ringraziandoti per aver guardato, scaricato e migliorato il mio progetto, sarei incredibilmente felice di ricevere il tuo aiuto, è il mio primo progetto in Kotlin ed anche la mia prima app Android. Studio informatica all'ITIS Belluzzi, sono al terzo anno e per tale ragione non ho molta esperienza con la programmazione, ma il particolare con Kotlin, che studio quando ho un po' di tempo libero attraverso i Codelabs di Google. L'anno scolastico precedente ho partecipato alla tua assemblea d'Istituto e da lì ho cominciato ad appassionarmi a Kotlin. Grazie ancora per l'attenzione.

**Comment by AleP04** [comment]
> Ciao ho trovato il tuo progetto molto interessante. Ho deciso di scaricarlo e di metterci un po' le mani. Ho sistemato grossi problemi grafici e snellito l'xml così da rendere l'app più reattiva e alla portata di tutti gli schermi.
> Fammi sapere se ti interessa il mio aiuto.

Buon pomeriggio, comincio ringraziandoti per aver guardato, scaricato e migliorato il mio progetto, sarei incredibilmente felice di ricevere il tuo aiuto, è il mio primo progetto in Kotlin ed anche la mia prima app Android. Studio informatica all'ITIS Belluzzi, sono al terzo anno e per tale ragione non ho molta esperienza con la programmazione, ma il particolare con Kotlin, che studio quando ho un po' di tempo libero attraverso i Codelabs di Google. L'anno scolastico precedente ho partecipato alla tua assemblea d'Istituto e da lì ho cominciato ad appassionarmi a Kotlin. Grazie ancora per l'attenzione.

**Comment by fctaddia** [comment]
Perfetto direi che puoi procedere ad aggiungermi come contributor alla tua repository così che possa fare pull, push e commit

Piccolo consiglio. Studiati molto bene Java visto che Kotlin si basa su questo linguaggio. Non studiarti Kotlin da zero senza basi di Java.

**Comment by AleP04** [comment]
> Perfetto direi che puoi procedere ad aggiungermi come contributor alla tua repository così che possa fare pull, push e commit
> 
> Piccolo consiglio. Studiati molto bene Java visto che Kotlin si basa su questo linguaggio. Non studiarti Kotlin da zero senza basi di Java.

Fatto, grazie mille del consiglio, ti ho aggiunto, perdonami se sbaglio qualcosa, ma ho appena iniziato a usare Git e GitHub.

**Comment by fctaddia** [comment]
Perfetto entro la settimana pusho gli update.

 Se vuoi nel weekend posso farti un po' di videolezione su android git

**Comment by AleP04** [comment]
> Perfetto entro la settimana pusho gli update.
> 
>  Se vuoi nel weekend posso farti un po' di videolezione su android git

A me farebbe molto piacere, grazie mille della proposta.
Io nel weekend a meno del Sabato mattina sono libero, dimmi tu quale orario preferisci e qual'è la tua tariffa.
Se vuoi un contatto ti lascio il mio indirizzo e-mail, lo stesso presente nelle info del mio profilo GitHub.

**Comment by AleP04** [comment]
> Perfetto entro la settimana pusho gli update.
> 
>  Se vuoi nel weekend posso farti un po' di videolezione su android git

Se vuoi un contatto ti lascio il mio indirizzo e-mail, lo stesso presente nelle info del mio profilo GitHub.
